#starting options have parameter --runmod default is:development
development:
  default:
    regional_node: oss-cn-beijing.aliyuncs.com
    id: ''
    key: ''
    bucket: meicanyun-test
    download_site: http://meicanyun-test.oss-cn-beijing.aliyuncs.com/
    download_image_site: ''
    image_prefix: devimg/
    image_max_length: 8388608 # 单位B 8388608B=8M